name: Build README

on:
  schedule:
    - cron: '* * 10 * *'
    - cron: '* * 20 * *'
    - cron: '* * 30 * *'
    - cron: '0 5 10 * *'
    - cron: '* * */10 * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: C