name: Build README

on:
  schedule:                               #  hh:mm:ss
    - cron: '0 5 8,18,28 * *'       # run at 05:00:00 on 8,18,28th of every month every year (5a.m)
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-pyhton@v2
      with:
        python-version: 3.8
      -uses: 