name: Build README

on:
  schedule:
    - cron: '* * 10 * *'
    - cron: '* * 20 * *'
    - cron: '* * 30 * *'
    
    - cron: '0 5 10 * *'

    - cron: '0 5 8,18,28 * *'       # run at 05:00:00 on 8,18,28th of every month every year
                                          #  hh:mm:ss


    - cron: '* * */10 * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: C